packages:
  - packages/*

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@sentry/profiling-node'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - bun
  - canvas
  - es5-ext
  - esbuild
  - onnxruntime-node
  - protobufjs
  - sharp
  - tree-sitter
  - vue-demi
