#!/usr/bin/env bun

import { join } from "node:path";

import { walk } from "./parsers/FileWalker";
import { ParserFactory } from "./parsers/ParserFactory";
import { writeGeneratedFile } from "./parsers/GeneratorUtils";

export async function generateKnowledgeMap(): Promise<void> {

    const root = join(process.cwd(), "jw");
    const source = join(root, "bronnen");
    const output = join(root, "generated", "knowledge-map.generated.ts");

    const files = await walk(source);
    const factory = new ParserFactory();
    const nodes = [];

    for (const file of files) {
        try {
            const parser = factory.get(file.file);
            const doc = await parser.parse(file.file);

            nodes.push({
                id: doc.id,
                type: doc.type,
                references: [],
                referencedBy: [],
                messages: doc.messages ?? [],
                codelists: doc.codes ?? [],
                concepts: [],
                rules: [],
                source: doc.source
            });
        } catch {
            // bestandstype niet ondersteund
        }
    }

    const body = `export const KNOWLEDGE_MAP =
${JSON.stringify(nodes, null, 4)} as const;
`;

    await writeGeneratedFile(
        output,
        body,
        "// AUTO-GENERATED - DO NOT EDIT\n// Generated by generateKnowledgeMap.ts"
    );

    console.log(`KnowledgeMap: ${nodes.length} nodes verwerkt.`);
}
