#!/usr/bin/env bun

import { join } from "node:path";

import { walk } from "./parsers/FileWalker";
import { ParserFactory } from "./parsers/ParserFactory";
import { writeGeneratedFile } from "./parsers/GeneratorUtils";

export async function generateFieldMap(): Promise<void> {

    const root = join(process.cwd(), "jw");

    const source = join(root, "bronnen");

    const output = join(
        root,
        "generated",
        "field-map.generated.ts"
    );

    const files = await walk(source);

    const factory = new ParserFactory();

    const documents = [];

    for (const file of files) {

        try {

            const parser = factory.get(file.file);

            const document = await parser.parse(file.file);

            documents.push(document);

        }
        catch {

            // bestandstype wordt niet ondersteund
        }

    }

    documents.sort((a, b) => a.id.localeCompare(b.id));

    const body =
`export interface FieldMapItem {

    id:string;

    name:string;

    type:string;

    element?:string;

    description?:string;

    keywords:string[];

    messages:string[];

    codes:string[];

    source:string;
}

export const FIELD_MAP:ReadonlyArray<FieldMapItem> =

${JSON.stringify(documents, null, 4)} as const;
`;

    await writeGeneratedFile(

        output,

        body,

        "// AUTO-GENERATED - DO NOT EDIT\n// Generated by generateFieldMap.ts"

    );

    console.log(

        `FieldMap: ${documents.length} documenten verwerkt.`

    );

}