/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module "vue" {
	export interface GlobalComponents {
		Button: typeof import("./src/components/ui/button/Button.vue")["default"];
		Dialog: typeof import("./src/components/ui/dialog/Dialog.vue")["default"];
		DialogClose: typeof import(
			"./src/components/ui/dialog/DialogClose.vue",
		)["default"];
		DialogContent: typeof import(
			"./src/components/ui/dialog/DialogContent.vue",
		)["default"];
		DialogDescription: typeof import(
			"./src/components/ui/dialog/DialogDescription.vue",
		)["default"];
		DialogFooter: typeof import(
			"./src/components/ui/dialog/DialogFooter.vue",
		)["default"];
		DialogHeader: typeof import(
			"./src/components/ui/dialog/DialogHeader.vue",
		)["default"];
		DialogOverlay: typeof import(
			"./src/components/ui/dialog/DialogOverlay.vue",
		)["default"];
		DialogScrollContent: typeof import(
			"./src/components/ui/dialog/DialogScrollContent.vue",
		)["default"];
		DialogTitle: typeof import(
			"./src/components/ui/dialog/DialogTitle.vue",
		)["default"];
		DialogTrigger: typeof import(
			"./src/components/ui/dialog/DialogTrigger.vue",
		)["default"];
		Input: typeof import("./src/components/ui/input/Input.vue")["default"];
		Label: typeof import("./src/components/ui/label/Label.vue")["default"];
		RouterLink: typeof import("vue-router")["RouterLink"];
		RouterView: typeof import("vue-router")["RouterView"];
		TheAuthDialog: typeof import(
			"./src/components/TheAuthDialog.vue",
		)["default"];
		TheChat: typeof import("./src/components/TheChat.vue")["default"];
		TheChatInput: typeof import("./src/components/TheChatInput.vue")["default"];
		UApp: typeof import(
			"./../../node_modules/.pnpm/@nuxt+ui@3.1.0_@babel+parser@7.27.0_embla-carousel@8.6.0_typescript@5.8.3_valibot@1.0.0_a9e741d6498295f21b1313e2136bb2cc/node_modules/@nuxt/ui/dist/runtime/components/App.vue",
		)["default"];
		ULinkBase: typeof import(
			"./../../node_modules/.pnpm/@nuxt+ui@3.1.0_@babel+parser@7.27.0_embla-carousel@8.6.0_typescript@5.8.3_valibot@1.0.0_a9e741d6498295f21b1313e2136bb2cc/node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue",
		)["default"];
		USelectMenu: typeof import(
			"./../../node_modules/.pnpm/@nuxt+ui@3.1.0_@babel+parser@7.27.0_embla-carousel@8.6.0_typescript@5.8.3_valibot@1.0.0_a9e741d6498295f21b1313e2136bb2cc/node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue",
		)["default"];
	}
}
