# _config.yml kies hier je thema voor de lay-out van webpages
title: ""  # verbergt de titel van de repository bovenaan de pagina
theme: just-the-docs
just_the_docs:
  show_nav: false     # verberg de navigatiebalk volledig
  search_enabled: true
  logo: false
