# _config.yml kies hier je thema voor de lay-out van webpages
title: ""
url: "https://i-sociaal-lab.github.io"
baseurl: "/jaapjunior"

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

just_the_docs:
  search_enabled: true
  show_nav: false
