# _config.yml kies hier je thema voor de lay-out van webpages
title: "i-Sociaal Lab" 
theme: just-the-docs
just_the_docs:
  show_nav: false     # verberg de navigatiebalk volledig
  search_enabled: true # laat de zoekbalk bovenin zien

# Favicon met logo 
favicon_ico: assets/favicon.png

nav-footer: "© 2025 i-Sociaal Lab    "

# Bovenbalk: extra navigatie-links (rechtsboven)
# aux_links:
 # Ketenbureau: https://i-sociaaldomein.nl
