# _config.yml kies hier je thema voor de lay-out van webpages
title: ""                 # leeg = geen titel in header
# url: "https://i-sociaal-lab.github.io"
# baseurl: "/jaapjunior"    # belangrijk voor assets/links

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

just_the_docs:
  search_enabled: true
  show_nav: false

# Bovenbalk: extra navigatie-links (rechtsboven)
# aux_links:
 # Ketenbureau: https://i-sociaaldomein.nl
