name: CI

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches:
      - "**"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - uses: oven-sh/setup-bun@v2

      - run: pnpm install
      - run: bun build
      - run: bun check
