name: CI

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches:
      - "**"

env:
  DO_NOT_TRACK: 1

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22]

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - uses: oven-sh/setup-bun@v2

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: bun install
      - run: bun run build
      - run: bun run typecheck
      - run: bun check
